name: compiler

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - nice

library:
  source-dirs:
    - lib/
  dependencies:
    - base
    - containers
    - semigroups
    - protolude
    - parsec
    - parsec3-numbers
    - text
    - wl-pprint

executables:
  nice:
    main: src/Main.hs
    dependencies:
      - compiler

